SOURCES = Main.cpp Camera.cpp Color.cpp Helpers.cpp Matrix4.cpp Mesh.cpp Rotation.cpp Scaling.cpp Scene.cpp tinyxml2.cpp Translation.cpp Triangle.cpp Vec3.cpp Vec4.cpp
all:
	g++ -g -Wall -o -O3 rasterizer $(SOURCES)
